### ISSUE TITLE
Update Deprecated Lambda Runtimes nodejs 12.x

### ISSUE THREAD

**Issue by constseche** [aws-samples/aws-iam-identity-center-extensions#101]
The following stacks:  
1. env-aws-sso-extensions-for-enterprise-preSolutionArtefactsStack
2.  env-aws-sso-extensions-for-enterprise-solutionartefactsStack   

create lambda functions (names are env-aws-sso-extensions-fo*) with deprecated runtimes nodejs12.x

we need to update them nodejs16.x

**Comment by leelalagudu** [comment]
Hi @constseche , we had already updated Lambda runtimes for all lambda functions that are created specifically for the solution. The lambda functions that you see in those 2 stacks using nodejs 12.x are provider functions that CDK deploys by default in an AwsCustomResource construct. [We use this for cross-account and region SSM parameter reading](https://github.com/aws-samples/aws-sso-extensions-for-enterprise/blob/main/lib/constructs/ssm-param-reader.ts#L44)

There's already an issue being tracked in https://github.com/aws/aws-cdk/issues/19117 , and as and when the CDK nightly run fixes this issue, we will upgrade our solution to use that CDK version. 

Hope this helps. Please let us know if you need any other data
