### ISSUE TITLE
Use NODEJS_20_X

### ISSUE THREAD

**Issue by trivikr** [aws-samples/aws-iam-identity-center-extensions#125]
### Use Case

Lambda NODEJS_16_X runtime is used at multiple places https://github.com/search?q=repo%3Aaws-samples%2Faws-iam-identity-center-extensions%20NODEJS_16_X&type=code

It's deprecated as of `Jun 12, 2024` and function create will be blocked on `Feb 28, 2025`.
Lambda Supported Runtimes https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html

### Proposed Solution

Use NODEJS_20_X in use cases and patterns, which [was made available on Nov 15, 2023](https://aws.amazon.com/blogs/compute/node-js-20-x-runtime-now-available-in-aws-lambda/)

**Comment by jmejco** [comment]
Updated in v3.1.9
