### ISSUE TITLE
Unable to deploy 3.1.8

### ISSUE THREAD

**Issue by DivyaKK-Pfizer** [aws-samples/aws-iam-identity-center-extensions#128]
The pipeline failed in the last stage, and we got this error in stack env-aws-sso-extensions-for-enterprise-deploySolutionArtefacts

Resource handler returned message: "The runtime parameter of nodejs14.x is no longer supported for creating or updating AWS Lambda functions. We recommend you use a supported runtime while creating or updating functions. (Service: Lambda, Status Code: 400)"

We see one of the lambda in the cf template (env-aws-sso-extensions-for-enterprise-preSolutionArtefactsStack) is mapped to runtime nodejs14.x and AWS does not support it.

**Comment by jmejco** [comment]
@DivyaKK-Pfizer Thank you for raising. I will be releasing a maintenance update to upgrade the Lambda runtime by mid September.

**Comment by DivyaKK-Pfizer** [comment]
@jmejco ...Any update for us on this and by when the release will be available.

**Comment by jmejco** [comment]
@DivyaKK-Pfizer Apologies for the delay. I have released v3.1.9 that updates the NodeJS runtime to v20. For the changelog, see https://github.com/aws-samples/aws-iam-identity-center-extensions/releases/tag/v3.1.9
